apiVersion: v1
kind: Service
metadata:
  labels:
    run: alpha
  name: alpha
spec:
  ports:
  - nodePort: 31552
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    run: alpha
  type: NodePort
