apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: alpha
  name: alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      run: alpha
  template:
    metadata:
      labels:
        run: alpha
    spec:
      containers:
      - image: alpha
        imagePullPolicy: Never
        name: alpha
        ports:
        - containerPort: 8081
          protocol: TCP